spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.731596c579d3b990
            clientSecret: 1a16900f622b3b74d6d2e1efa40c53a63ad8705d
          google:
            clientId: 758010925210-nrg86c4p3bcn2u8ui8d5j5f79dlh4agj.apps.googleusercontent.com
            clientSecret: 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
            scope: openid,profile,email
      resource-server:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: com.bk.oauth2.sociallogin.common.MyImplicitNamingStrategy
        physical-strategy: com.bk.oauth2.sociallogin.common.MyPhysicalNamingStrategy
    open-in-view: false
    database: MYSQL
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eng
    username: root
    password: local
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true